export default {
  START_APP: 'START_APP',
  UPDATE_DATA_REQUEST: 'UPDATE_DATA_REQUEST',
  UPDATE_DATA: 'UPDATE_DATA',
  ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO: 'DELETE_TODO',
  SEARCH_TODO: 'SEARCH_TODO',
  SET_STATUS_TODO_REQUEST: 'SET_STATUS_TODO_REQUEST',
  SET_STATUS_TODO: 'SET_STATUS_TODO',
  FILTER_TODO: 'FILTER_TODO',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
};
